name: Mirror to GitLab

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - master-sync
  delete:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full repo (all history + refs)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror push to GitLab
        env:
          GITLAB_PAT: ${{ secrets.GITLAB_PAT }}
        run: |
          git remote add testing "https://x-access-token:${{ secrets.GIT_PAT }}@github.com/zzahkaboom24/yolks-testing.git"
          
          git remote update --prune origin
          
          git push testing --force master-sync:master-sync
          git push testing --force --tags
